services:
  davmail:
    build:
      .
    container_name: davmail
    volumes:
      - ./config_davmail/davmail.properties:/etc/davmail/davmail.properties
      - ./config_davmail/davmail.log:/var/log/davmail.log
    restart: unless-stopped
    network_mode: host
